version: "3.7"
services:
  pz-server:
    image: danixu86/project-zomboid-dedicated-server:latest
    restart: unless-stopped
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "27015:27015/tcp"
